version: '3.4'
services:
  db:
    image: mysql:5.7
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: forum
    ports:
      - 3307:3306
  api:
    image: adoptopenjdk/openjdk11
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/forum
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker
      JWS_SECRET: 123456
      SPRING_PROFILES_ACTIVE: prod
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 8081:8080