version: '3.4'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres10"
      POSTGRES_DB: "forum"
    ports:
      - "5432:5432"
  api:
    image: adoptopenjdk/openjdk11
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/forum
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres10
      JWS_SECRET: 123456
      SPRING_PROFILES_ACTIVE: prod
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 8081:8080